[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
dist-name = 'MPh'
module = 'mph'
author = 'John Hennig'
requires = ['JPype1', 'NumPy']
requires-python = '>=3.6'
license = 'MIT'
home-page = 'https://github.com/MPh-py/MPh'
description-file = 'pypi.md'
keywords = 'finite elements, computer simulation, physics, multiphysics, Comsol'
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Programming Language :: Python :: 3',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Topic :: Scientific/Engineering :: Physics',
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'License :: OSI Approved :: MIT License']

[tool.flit.metadata.requires-extra]
doc = ['Sphinx', 'Furo', 'MyST-parser', 'CommonMark']
test = ['pyTest', 'pyTest-cov', 'coverage-badge', 'flake8']

[tool.flit.metadata.urls]
Documentation = 'https://mph.readthedocs.io'
Source = 'https://github.com/MPh-py/MPh'
